name: Run Tests

on:
  pull_request:
    branches:
        - main

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Run Jest tests
        run: pnpm run test
