name: Run Tests

on:
  pull_request:
    branches:
        - main

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run tests
        run: pnpm test
